### ISSUE TITLE
Support multi-node ETCD

### ISSUE THREAD

**Issue by esnellman** [Percona-Lab/proxysql-docker#1]
Let DISCOVERY_SERVICE support a comma delimited list of host:port address, where each is a etcd node.

**Comment by Qanah** [comment]
please help me with this cluster 

see this https://www.percona.com/doc/percona-xtradb-cluster/LATEST/install/docker.html

```
version: '3.8'

services:

  etcd:
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=ETCD]
      placement:
        constraints: [node.role == manager]
    image: elcolio/etcd:latest
    ports:
      - 2379:2379
      - 2380:2380
      - 4001:4001
      - 7001:7001
    networks:
      - pxc_distributed

  proxy:
    depends_on:
      - etcd
    image: perconalab/proxysql
    networks:
      - front
      - pxc_distributed
    ports:
      - 3306:3306
      - 6032:6032
    environment:
      MYSQL_ROOT_PASSWORD: root
      DISCOVERY_SERVICE: etcd:2379
      CLUSTER_NAME: pxc-cluster
      MYSQL_PROXY_USER: proxyuser
      MYSQL_PROXY_PASSWORD: s3cret

  pxc-node1:
    depends_on:
      - etcd
      - proxy
    deploy:
#      resources:
#        limits:
#          memory: 1GB
      placement:
        constraints:
          - node.labels.pxc-node1==true
    image: percona/percona-xtradb-cluster:8.0
    volumes:
      - pxc-node1-data:/var/lib/mysql
      - ~/pxc-docker-test/cert:/cert
      - ~/pxc-docker-test/config:/etc/percona-xtradb-cluster.conf.d
    networks:
      - pxc_distributed
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      DISCOVERY_SERVICE: etcd:2379
      CLUSTER_NAME: pxc-cluster
      MYSQL_PROXY_USER: proxyuser
      MYSQL_PROXY_PASSWORD: s3cret

  pxc-node2:
    depends_on:
      - etcd
      - proxy
      - pxc-node1
    deploy:
#      resources:
#        limits:
#          memory: 1GB
      placement:
        constraints:
          - node.labels.pxc-node2==true
    image: percona/percona-xtradb-cluster:8.0
    volumes:
      - pxc-node2-data:/var/lib/mysql
      - ~/pxc-docker-test/cert:/cert
      - ~/pxc-docker-test/config:/etc/percona-xtradb-cluster.conf.d
    networks:
      - pxc_distributed
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      DISCOVERY_SERVICE: etcd:2379
      CLUSTER_NAME: pxc-cluster
      CLUSTER_JOIN: pxc-node1
      MYSQL_PROXY_USER: proxyuser
      MYSQL_PROXY_PASSWORD: s3cret

  pxc-node3:
    depends_on:
      - etcd
      - proxy
      - pxc-node1
    deploy:
#      resources:
#        limits:
#          memory: 1GB
      placement:
        constraints:
          - node.labels.pxc-node3==true
    image: percona/percona-xtradb-cluster:8.0
    volumes:
      - pxc-node3-data:/var/lib/mysql
      - ~/pxc-docker-test/cert:/cert
      - ~/pxc-docker-test/config:/etc/percona-xtradb-cluster.conf.d
    networks:
      - pxc_distributed
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      DISCOVERY_SERVICE: etcd:2379
      CLUSTER_NAME: pxc-cluster
      CLUSTER_JOIN: pxc-node1
      MYSQL_PROXY_USER: proxyuser
      MYSQL_PROXY_PASSWORD: s3cret

  pxc-node4:
    depends_on:
      - etcd
      - proxy
      - pxc-node1
    deploy:
#      resources:
#        limits:
#          memory: 1GB
      placement:
        constraints:
          - node.labels.pxc-node4==true
    image: percona/percona-xtradb-cluster:8.0
    volumes:
      - pxc-node4-data:/var/lib/mysql
      - ~/pxc-docker-test/cert:/cert
      - ~/pxc-docker-test/config:/etc/percona-xtradb-cluster.conf.d
    networks:
      - pxc_distributed
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      DISCOVERY_SERVICE: etcd:2379
      CLUSTER_NAME: pxc-cluster
      CLUSTER_JOIN: pxc-node1
      MYSQL_PROXY_USER: proxyuser
      MYSQL_PROXY_PASSWORD: s3cret

volumes:
  pxc-node1-data:
  pxc-node2-data:
  pxc-node3-data:
  pxc-node4-data:

networks:
  pxc_distributed:
    driver: overlay
  front:
    driver: overlay
```
